export const EXPERIENCE_LIST = [
  {
    name: 'Costco Wholesale',
    role: 'Frontend Developer Consultant',
    start: 'Dec 2023',
    end: 'Present',
    imgSrc: '/costco_logo.jpg',
    imgAlt: 'Costco logo',
  },
  {
    name: 'CaringBridge',
    role: 'Frontend Developer Consultant',
    start: 'Apr 2021',
    end: 'Dec 2023',
    imgSrc: '/caringbridge_logo.jpg',
    imgAlt: 'CaringBridge logo',
  },
  {
    name: 'West Ed',
    role: 'Full Stack Developer Consultant',
    start: 'Jun 2020',
    end: 'Nov 2020',
    imgSrc: '/west_ed_logo.png',
    imgAlt: 'West Ed logo',
  },
  {
    name: 'Delta Air Lines',
    role: 'Full Stack Developer Consultant',
    start: 'Mar 2020',
    end: 'Jun 2020',
    imgSrc: '/delta_air_lines_logo.jpg',
    imgAlt: 'Delta logo',
  },
  {
    name: 'AccuWeather',
    role: 'Full Stack Developer Consultant',
    start: 'May 2019',
    end: 'Nov 2019',
    imgSrc: '/accuweather_logo.jpg',
    imgAlt: 'AccuWeather logo',
  },
  {
    name: 'Cargill',
    role: 'Full Stack Developer Consultant',
    start: 'Jun 2018',
    end: 'Jan 2019',
    imgSrc: '/cargill_logo.jpg',
    imgAlt: 'Cargill logo',
  },
  {
    name: 'Best Buy',
    role: 'Frontend Developer Consultant',
    start: 'Apr 2017',
    end: 'May 2018',
    imgSrc: '/best_buy_logo.jpg',
    imgAlt: 'Best Buy logo',
  },
  {
    name: 'Surescripts',
    role: 'Senior Software Engineer',
    start: 'Mar 2015',
    end: 'Apr 2017',
    imgSrc: '/surescripts_logo.jpg',
    imgAlt: 'Surescripts logo',
  },
  {
    name: 'Thomson Reuters',
    role: 'Senior Software Engineer',
    start: 'Jun 2012',
    end: 'Mar 2015',
    imgSrc: '/thomson_reuters_logo.jpg',
    imgAlt: 'Thomson Reuters logo',
  },
]
